<% # Make sure the local copy of the driver is loaded %>
<% lib = File.expand_path('../lib', __FILE__) %>
<% $LOAD_PATH.unshift(lib) unless $LOAD_PATH.include?(lib) %>
---
driver:
  name: docker
  provision_command: curl -L https://www.chef.io/chef/install.sh | bash
  use_sudo: false

provisioner:
  name: chef_zero

platforms:
#- name: ubuntu-12.04
#- name: ubuntu-14.04
#- name: ubuntu-16.04
#- name: centos-6
- name: centos-6.7
#- name: centos-7
#- name: debian
#- name: arch
#  driver:
#    image: base/archlinux
#    provision_command: true
#- name: unknown
#  driver:
#    image: ubuntu:12.04
#    platform: ubuntu
#- name: dockerfile
#  driver:
#    username: dockerfile
#    password: dockerfile
#    dockerfile: test/Dockerfile
#    run_command: /sbin/init

suites:
  - name: default
    run_list:
#      - recipe[kitchen-docker-workstation::default]
      - recipe[kitchen-docker-workstation::setup]
    verifier:
      inspec_tests:
        - test/recipes
    attributes:
